
class Variables(object):
    
    #Months
    Enero = '1'
    Febrero = '2'
    Marzo = '3'
    Abril = '4'
    Mayo = '5'
    Junio = '6'
    Julio = '7'
    Agosto = '8'
    Septiembre = '9'
    Octubre = '10'
    Noviembre = '11'
    Diciembre = '12'
    
    # Country
    United_States = '21'
    
    # States
	
    Arizona = '3'
    Alabama = '1'						
    Alaska = '2'
    Arkansas = '4'
    California = '5'
    Colorado = '6'
    Connecticut = '7'
    Delaware = '8'
    District_of_Columbia = '53'
    Florida = '9'
    Georgia = '10'
    Hawaii = '11'
    Idaho = '12'
    Illinois = '13'
    Indiana = '14'
    Iowa = '15'
    Kansas = '16'
    Kentucky = '17'
    Louisiana = '18'
    Maine = '19'
    Maryland = '20'
    Massachusetts = '21'
    Michigan = '22'
    Minnesota = '23'
    Mississippi = '24'
    Missouri = '25'
    Montana = '26'
    Nebraska = '27'
    Nevada = '28'
    New_Hampshire = '29'
    New_Jersey = '30'
    New_Mexico = '31'
    New_York = '32'
    North_Carolina = '33'
    North_Dakota = '34'
    Ohio = '35'
    Oklahoma = '36'
    Oregon = '37'
    Pennsylvania = '38'
    Puerto_Rico = '51'
    Rhode_Island = '39'
    South_Carolina = '40'
    South_Dakota = '41'
    Tennessee = '42'
    Texas = '43'
    US_Virgin_Islands = '52'
    Utah = '44'
    Vermont = '45'
    Virginia = '46'
    Washington = '47'
    West_Virginia = '48'
    Wisconsin = '49'
    Wyoming = '50'